INSERT INTO ejemplo.Plantel(Id_Plantel , NombrePlantel , DireccionPlantel , EmailPlantel , TelefonoPlantel , Id_Municipio)
values (1 , 'Nezahualcóyotl' , 'Circuito Rey Neza S/N y 4ª. Av., Col. Benito Juárez, Cd. Nezahualcóyotl, Estado de México' , 'neza2@conalepmex.edu.mx' , '5557313906' , 1),
       (2 , 'Coacalco' , 'Bosque Central No. 179, Fracc. Bosques del Valle 2a sección Coacalco, Estado de México C.P. 55717' , 'coacalcoconalepmex.edu.mx' , '5526441334' , 2 ),
       (3 , 'Cuautitlán' , 'Av. 1º de Mayo No. 2, Col. Centro Urbano, Cuautitlán Izcalli, Estado de México C.P. 54720' , 'cuautitlan@conalepmex.edu.mx' , '5558801268' , 3 ),
       (4 , 'Los reyes la paz' , ' Carretera México-Texcoco Km. 25.5 esquina Camino a las Minas,Los Reyes La Paz, Estado de México C.P. 56400.' , 'losreyeslapaz@conalepmex.edu.mx' , '5526136396' , 4) ,
       (5 , 'Lerma' , ' C. Juan Aldama No. 10 Col. Guadalupe Lerma, Estado de México C.P. 52000' , 'lerma@conalepmex.edu.mx' , '7282851976' , 5) ,
       (6 , 'Nicolas Romero' , 'Calle Margarita Maza de Juárez S/N, Col. Juárez 1ra Sección, Nicolás Romero, Estado de México C.P. 54400' , 'niclasromero@copnalepmex.edu.mx' , '5558230224' , 6),
       (7 , 'Ecatepec I' , ' Cerrada Conalep s/n, Col. Cd. Cuauhtémoc, Ecatepec de Morelos, Estado de México, C.P. 55067' , 'ecatepec1@conalepmex.edu.mx' , '5588790912' , 7),
       (8 , 'tlalnepantla II' , ' C. Alpino Tlaloc S/N, col. la Presa 3ª Sección Tlalnepantla de Baz, Estado de México C.P. 54180' , 'tlalne2@conalepmex.edu.mx' , '5553104639' , 8) ,
       (9 , 'Villa victoria' , ' C. P. Yolanda Victoria Mercado. Dirección: Carretera Villa Victoria-El Oro San Pedro del Rincón Km 2.5 Villa Victoria, Estado de México C.P. 50960.' , 'villavictoria@conalepmex.edu.mx' , '7262515248' , 9) , 
       (10 , 'Huixquilucan' , ' km. 1.5 carr. Huixquilucan-Zacamulpa, Col. San Juan Bautista, Municipio. Huxquilucan, Estado de México C.P. 54700.' , 'huixquilucan@conalepmex.edu.mx' , '5582840944' , 10);